Traceback (most recent call last):
  File "/home/fjellman/hpc-course/first-hpc-project/code/computation.py", line 23, in <module>
    with h5py.File(f'../output/results_n-procs={N_PROCS}.h5', 'w') as f:
  File "/ssoft/spack/syrah/v2/opt/spack/linux-rhel9-skylake_avx512/gcc-11.3.0/py-h5py-3.6.0-ojxqusbkarnh3gomelnre5ssbjah6qry/lib/python3.10/site-packages/h5py/_hl/files.py", line 507, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
  File "/ssoft/spack/syrah/v2/opt/spack/linux-rhel9-skylake_avx512/gcc-11.3.0/py-h5py-3.6.0-ojxqusbkarnh3gomelnre5ssbjah6qry/lib/python3.10/site-packages/h5py/_hl/files.py", line 226, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 126, in h5py.h5f.create
BlockingIOError: [Errno 11] Unable to create file (unable to lock file, errno = 11, error message = 'Resource temporarily unavailable')
slurmstepd: error: *** JOB 4084584 ON h133 CANCELLED AT 2024-10-08T13:13:30 DUE TO TIME LIMIT ***
slurmstepd: error: *** STEP 4084584.0 ON h133 CANCELLED AT 2024-10-08T13:13:30 DUE TO TIME LIMIT ***
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
